In [ ]:
import pandas as pd
df = pd.read_csv('world.csv')
df

In [ ]:
df.info()

In [ ]:
df1=df.reindex(columns=['洲名','國家','日期','總確診數','新增確診數','總人口數'])
df1

In [ ]:
#依據值的搜尋
#亞洲
df1[df1['洲名']=='亞洲']

In [ ]:
#依據值的搜尋
#台灣
dftw=df[df['國家']=='台灣']
display(dftw)

In [13]:
dftw['日期']>='2021-01-01'
dftw['日期']<'2022-01-01'

163986     True
163987     True
163988     True
163989     True
163990     True
          ...
164884    False
164885    False
164886    False
164887    False
164888    False
Name: 日期, Length: 903, dtype: bool

In [ ]:
dftw2021=dftw[(dftw['日期']>='2021-01-01')&(dftw['日期']<'2022-01-01')]
dftw2021

In [ ]:
dftw2021[dftw2021['新增確診數'] >= 100]

In [19]:
dftw[dftw['新增確診數']>=10000]

,ID,iso_code,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
164819,164820,TWN,亞洲,台灣,2022-04-28,88446,11508,6457.571,860,2,...,102740.0,219.28,82.68,26.85,23855008,42.2,8.353,80.46,14835,5.02
164820,164821,TWN,亞洲,台灣,2022-04-29,100753,12307,7664.714,862,2,...,96087.0,219.79,82.74,26.85,23855008,42.2,8.353,80.46,14835,5.85
164821,164822,TWN,亞洲,台灣,2022-04-30,115883,15130,9226.429,865,3,...,93648.0,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,6.87
164822,164823,TWN,亞洲,台灣,2022-05-01,132955,17072,10926.714,868,3,...,91208.0,220.18,82.79,26.85,23855008,42.2,8.353,80.46,14835,8.02
164824,164825,TWN,亞洲,台灣,2022-05-03,173942,40987,15131.429,876,8,...,81601.0,220.82,82.90,26.85,23855008,42.2,8.353,80.46,14835,10.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164884,164885,TWN,亞洲,台灣,2022-07-02,3837856,34807,37736.143,6868,96,...,85345.0,0.00,0.00,0.00,23855008,42.2,8.353,80.46,14835,258.17
164885,164886,TWN,亞洲,台灣,2022-07-03,3870528,32672,36740.429,6956,88,...,83512.0,243.72,88.80,0.00,23855008,42.2,8.353,80.46,14835,260.37
164886,164887,TWN,亞洲,台灣,2022-07-04,3893643,23115,35960.286,7025,69,...,80397.0,244.04,88.81,0.00,23855008,42.2,8.353,80.46,14835,261.94
164887,164888,TWN,亞洲,台灣,2022-07-05,3929627,35984,34755.571,7128,103,...,79776.0,244.41,88.82,0.00,23855008,42.2,8.353,80.46,14835,264.37
164888,164889,TWN,亞洲,台灣,2022-07-06,3964188,34561,33689.286,7223,95,...,75670.0,244.76,88.83,0.00,23855008,42.2,8.353,80.46,14835,266.71